version: '3'

services:
  web:
    build: ./
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/backend/app/app.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/house_account_local
    volumes:
      - ./:/app
    working_dir: /app/backend/app
    depends_on:
      - db

  db:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=password  # root ユーザーのパスワード
      - MYSQL_DATABASE=house_account_local         # 初期に作成するデータベース名
      - MYSQL_USER=root                   # 新しいユーザー名
      - MYSQL_PASSWORD=password           # 新しいユーザーのパスワード
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
