"""empty message

Revision ID: 0da2d0c58a30
Revises: e467c666ff47
Create Date: 2023-11-18 13:41:29.609192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da2d0c58a30'
down_revision = 'e467c666ff47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_expense_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_expense_items', schema=None) as batch_op:
        batch_op.drop_column('transaction_day')

    # ### end Alembic commands ###
