"""empty message

Revision ID: 564e1941aa56
Revises: 0da2d0c58a30
Create Date: 2023-12-09 00:28:02.076083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564e1941aa56'
down_revision = '0da2d0c58a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_expense_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_expense_items', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
